name: Snap.svg

markdown: redcarpet
pygments: true

source:       ./source
plugins:      ./source/_plugins
destination:  ./output

sass:
    syntax: scss        # scss|sass
    style:  compressed  # nested|expanded|compact|compressed